package net.spaceeye.vmod.utils.vs

import org.joml.Quaterniondc
import org.joml.Vector3dc
import org.valkyrienskies.core.api.ships.properties.ShipId
import org.valkyrienskies.core.apigame.constraints.*


fun VSAttachmentConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localPos0_: Vector3dc?, localPos1_: Vector3dc?, maxForce_: Double?, fixedDistance_: Double?) = VSAttachmentConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localPos0_ ?: localPos0, localPos1_ ?: localPos1, maxForce_ ?: maxForce, fixedDistance_ ?: fixedDistance)
fun VSPosDampingConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localPos0_: Vector3dc?, localPos1_: Vector3dc?, maxForce_: Double?, posDamping_: Double?) = VSPosDampingConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localPos0_ ?: localPos0, localPos1_ ?: localPos1, maxForce_ ?: maxForce, posDamping_ ?: posDamping)
fun VSRopeConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localPos0_: Vector3dc?, localPos1_: Vector3dc?, maxForce_: Double?, ropeLength_: Double?) = VSPosDampingConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localPos0_ ?: localPos0, localPos1_ ?: localPos1, maxForce_ ?: maxForce, ropeLength_ ?: ropeLength)
fun VSSlideConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localPos0_: Vector3dc?, localPos1_: Vector3dc?, maxForce_: Double?, localSlideAxis0_: Vector3dc?, maxDistBetweenPoints_: Double?) = VSSlideConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localPos0_ ?: localPos0, localPos1_ ?: localPos1, maxForce_ ?: maxForce, localSlideAxis0_ ?: localSlideAxis0, maxDistBetweenPoints_ ?: maxDistBetweenPoints)

fun VSFixedOrientationConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?) = VSFixedOrientationConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque)
fun VSHingeOrientationConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?) = VSHingeOrientationConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque)
fun VSHingeSwingLimitsConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?, minSwingAngle_: Double?, maxSwingAngle_: Double?) = VSHingeSwingLimitsConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque, minSwingAngle_ ?: minSwingAngle, maxSwingAngle_ ?: maxSwingAngle)
fun VSHingeTargetAngleConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?, targetAngle_: Double?, nextTargetAngle_: Double?) = VSHingeTargetAngleConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque, targetAngle_ ?: targetAngle, nextTargetAngle_ ?: nextTickTargetAngle)
fun VSSphericalSwingLimitsConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?, minSwingAngle_: Double?, maxSwingAngle_: Double?) = VSSphericalSwingLimitsConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque, minSwingAngle_ ?: minSwingAngle, maxSwingAngle_ ?: maxSwingAngle)
fun VSSphericalTwistLimitsConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?, minTwistAngle_: Double?, maxTwistAngle_: Double?) = VSSphericalTwistLimitsConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque, minTwistAngle_ ?: minTwistAngle, maxTwistAngle_ ?: maxTwistAngle)
fun VSRotDampingConstraint.copy(shipId0_: ShipId?, shipId1_: ShipId?, compliance_: Double?, localRot0_: Quaterniondc?, localRot1_: Quaterniondc?, maxTorque_: Double?, rotDamping_: Double?, rotDampingAxes_: VSRotDampingAxes?) = VSRotDampingConstraint(shipId0_ ?: shipId0, shipId1_ ?: shipId1, compliance_ ?: compliance, localRot0_ ?: localRot0, localRot1_ ?: localRot1, maxTorque_ ?: maxTorque, rotDamping_ ?: rotDamping, rotDampingAxes_ ?: rotDampingAxes)
